# Generated by Django 2.0.3 on 2018-04-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=200)),
                ('customeremail', models.CharField(db_index=True, max_length=200)),
                ('customerphone', models.CharField(max_length=200)),
                ('customeraddress', models.CharField(max_length=200)),
                ('customercity', models.CharField(max_length=200)),
                ('customerstate', models.CharField(max_length=200)),
                ('customerzip', models.CharField(max_length=200)),
                ('billingaddress', models.CharField(max_length=200)),
                ('billingcity', models.CharField(max_length=200)),
                ('billingstate', models.CharField(max_length=200)),
                ('billingzip', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
